name: Release Shortest Path Plugin

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build-release:
    environment: Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Set version from build number
        run: |
          export VERSION="1.0.${GITHUB_RUN_NUMBER}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build project
        run: |
          echo "Building project with version $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Collect commit messages since last tag
        id: changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "")
          if [ -z "$LAST_TAG" ]; then
            COMMITS=$(git log --pretty=format:"- %s")
          else
            COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s")
          fi
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a "${VERSION}" -m "Release v${VERSION}"
          git push origin "${VERSION}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: ${{ env.COMMITS }}

      - name: Install MinIO client
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv mc /usr/local/bin/

      - name: Configure MinIO client
        run: |
          mc alias set s3 ${{secrets.MINIO_URL}} ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}

      - name: Upload JAR to MinIO
        run: |
          JAR_FILE=$(find ./build/libs -name "shortest-path-*.jar" | head -n 1)
          echo "Uploading $JAR_FILE to MinIO..."
          mc cp "$JAR_FILE" s3/kraken-bootstrap-static/shortest-path-${VERSION}.jar